### ISSUE TITLE
Questions after installation

### ISSUE THREAD

**Issue by ribsousa** [melihovv/base64-image-decoder#3]
Hello, after installing via composer I have doubts:
Do I need to register provider?
How do I call this class in my controller?

**Comment by melihovv** [comment]
Hello
No, this package does not provide anything, that is why you don't need to register service provider
You can call this class as anything else class.
```php
$decoder = new \Melihovv\Base64ImageDecoder\Base64ImageDecoder($base64EncodedImage, $allowedFormats = ['jpeg', 'png', 'gif']);
```

**Comment by ribsousa** [comment]
I can use this
`use Melihovv\Base64ImageDecoder\Base64ImageDecoder;`

**Comment by melihovv** [comment]
Yes, you can
